---

- name: Include version specific variables for CentOS/RHEL
  include_vars: "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"

- name: Get service facts
  service_facts:

- name: Set fact before installation
  set_fact:
    redis_installed: false
  when: ansible_facts.services["redis.service"] is not defined

- name: Install the required packages
  package:
    name: "{{ os_required_packages }}"
    state: present
    use: auto

- name: Install the specified version of Redis from {{ redis_install_repo }} repo
  yum:
    name: "redis-{{ redis_version }}"
    enablerepo: "{{ redis_install_repo }}"
    state: present
  when: redis_version != "latest"

- name: Install the latest version of Redis from {{ redis_install_repo }} repo
  yum:
    name: redis
    enablerepo: "{{ redis_install_repo }}"
    state: present
  when: redis_version == "latest"

- name: Ensure sentinel data dir exists
  file:
    path: "{{ sentinel_data_dir }}"
    state: directory
    owner: redis
    group: redis
    mode: 0750
    recurse: true

- name: Transfer template files to the remote location
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: redis
    group: redis
    mode: 0644
    setype: redis_conf_t
  loop:
    - redis.conf
    - redis-sentinel.conf
  changed_when: false

- name: Ensure redis and sentinel ports are allowed for SELinux
  seport:
    ports: "{{ item }}"
    proto: tcp
    setype: redis_port_t
    state: present
  when:
    - ansible_selinux is defined
    - ansible_selinux | bool
  loop:
    - "{{ redis_port }}"
    - "{{ sentinel_port }}"

- name: Ensure firewalld is started and enabled
  service:
    name: firewalld
    state: started
    enabled: true
  changed_when: false

- name: Manage firewalld configuration
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - "{{ redis_port }}"
    - "{{ sentinel_port }}"

- name: Ensure limits are passed to systemd unit file
  lineinfile:
    path: /etc/systemd/system/redis.service.d/limit.conf
    regexp: "^{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  when:
    - os_required_limits is defined
    - (os_required_limits | length > 0)
  loop: "{{ os_required_limits }}"

- name: Include tasks from tuned.yml
  include_tasks: tuned.yml

- name: Include tasks from swap.yml
  include_tasks: swap.yml

- name: force systemd to reread configs
  systemd:
    daemon_reload: true

- name: start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - redis
    - redis-sentinel

- name: Set fact after installation to notify handlers
  set_fact:
    redis_installed: true
  when: ansible_facts.services["redis.service"] is defined

...
