---

- name: Include distribution specific variables
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Get service facts
  service_facts:

- name: Install the required packages
  apt:
    name: "{{ os_required_packages }}"
    state: present
    update_cache: true

- name: Install Redis block
  block:
    - name: Install the specified version of Redis
      apt:
        name: "redis-server={{ redis_version }}"
        state: present
      when: redis_version != "latest"

    - name: Install the specified version of Redis sentinel
      apt:
        name: "redis-sentinel={{ redis_version }}"
        state: present
      when: redis_version != "latest"

    - name: Install the latest version of Redis
      apt:
        name: redis-server
        state: present
      when: redis_version == "latest"

    - name: Install the latest version of Redis sentinel
      apt:
        name: redis-sentinel
        state: present
      when: redis_version == "latest"
