---

- name: Get service facts
  service_facts:

- name: Set fact before installation
  set_fact:
    redis_installed: false
  when: ansible_facts.services["redis.service"] is not defined

- name: Include distribution specific tasks
  include_tasks: "install_{{ ansible_os_family | lower }}.yml"

- name: Ensure redis port is allowed for SELinux
  seport:
    ports: "{{ redis_port }}"
    proto: tcp
    setype: redis_port_t
    state: present
  when:
    - ansible_selinux is defined
    - ansible_selinux | bool

- name: Firewalld enable block
  block:
    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true
      changed_when: false

    - name: Manage firewalld configuration
      firewalld:
        port: "{{ redis_port }}/tcp"
        permanent: true
        immediate: true
        state: enabled
  when: (firewalld_enabled | bool)

- name: Firewalld disable block
  block:
    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: stopped
        enabled: false
      changed_when: false
  when: (firewalld_enabled | bool)

- name: Ensure limits are passed to systemd unit file
  lineinfile:
    path: "{{ systemd_conf_path }}"
    state: present
    regexp: "^{{ item.key }}"
    insertbefore: '^Type'
    line: "{{ item.key }}={{ item.value }}"
  when:
    - os_required_limits is defined
    - (os_required_limits | length > 0)
  loop: "{{ os_required_limits }}"

- name: Include tasks from sentinel.yml
  include_tasks: sentinel.yml
  when:
    - sentinel_enabled | bool
    - not cluster_enabled | bool

- name: Include tasks from cluster.yml
  include_tasks: cluster.yml
  when:
    - cluster_enabled | bool
    - not sentinel_enabled | bool

- name: Include tasks from tuned.yml
  include_tasks: tuned.yml
  when:
    - (ansible_os_family | lower) == "redhat"
    - os_enable_tuned | bool

- name: Include tasks from sysctl.yml
  include_tasks: sysctl.yml
  when: (ansible_os_family | lower) == "debian"

- name: Include tasks from swap.yml
  include_tasks: swap.yml

- name: Force systemd to reread configs
  systemd:
    daemon_reload: true

- name: Transfer redis.conf template file to the remote location
  template:
    src: redis.conf.j2
    dest: "{{ redis_dest_file }}"
    owner: redis
    group: redis
    mode: 0644
    setype: redis_conf_t

- name: Start and enable redis on Redhat block
  block:
    - name: Start and enable redis service on RedHat
      service:
        name: redis
        state: restarted
        enabled: true
      changed_when: false

    - name: Start and enable redis-sentinel service on RedHat
      service:
        name: redis-sentinel
        state: restarted
        enabled: true
      when: sentinel_enabled | bool
      changed_when: false

    - name: Set fact after installation
      set_fact:
        redis_installed: true
      when: ansible_facts.services["redis.service"] is defined
  when: (ansible_os_family | lower) == "redhat"

- name: Start and enable redis on Debian block
  block:
    - name: Start and enable redis-server service on Debian
      service:
        name: redis-server
        state: restarted
        enabled: true
      changed_when: false

    - name: Start and enable redis-sentinel service on Debian
      service:
        name: redis-sentinel
        state: restarted
        enabled: true
      when: sentinel_enabled | bool
      changed_when: false

    - name: Set fact after installation
      set_fact:
        redis_installed: true
      when: ansible_facts.services["redis-server.service"] is defined
  when: (ansible_os_family | lower) == "debian"
