---

- name: Get service facts
  service_facts:

- name: Set fact before installation
  set_fact:
    redis_installed: false
  when: ansible_facts.services["redis.service"] is not defined

- name: Include distribution specific tasks
  include_tasks: "install_{{ ansible_os_family | lower }}.yml"

- name: Transfer redis.conf template file to the remote location
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: redis
    mode: 0644
    setype: redis_conf_t
  changed_when: false

- name: Ensure redis port is allowed for SELinux
  seport:
    ports: "{{ redis_port }}"
    proto: tcp
    setype: redis_port_t
    state: present
  when:
    - ansible_selinux is defined
    - ansible_selinux | bool

- name: Stop firewalld if desired by user
  service:
    name: firewalld
    state: stopped
    enabled: false
  when: not (firewalld_enabled | bool)

- name: Firewalld related block
  block:
    - name: Ensure firewalld is started and enabled
      service:
        name: firewalld
        state: started
        enabled: true
      changed_when: false

    - name: Manage firewalld configuration
      firewalld:
        port: "{{ redis_port }}/tcp"
        permanent: true
        immediate: true
        state: enabled
  when: (firewalld_enabled | bool)

- name: Ensure limits are passed to systemd unit file
  lineinfile:
    path: "{{ systemd_conf_path }}"
    regexp: "^{{ item.key }}"
    insertafter: '^[Service]'
    line: "{{ item.key }}={{ item.value }}"
  when:
    - os_required_limits is defined
    - (os_required_limits | length > 0)
  loop: "{{ os_required_limits }}"

- name: Include tasks from sentinel.yml
  include_tasks: sentinel.yml
  when:
    - sentinel_enabled | bool
    - not cluster_enabled | bool

- name: Include tasks from cluster.yml
  include_tasks: cluster.yml
  when:
    - cluster_enabled | bool
    - not sentinel_enabled | bool

- name: Include tasks from tuned.yml
  include_tasks: tuned.yml

- name: Include tasks from swap.yml
  include_tasks: swap.yml

- name: Force systemd to reread configs
  systemd:
    daemon_reload: true

- name: Start and enable redis on Redhat block
  block:
    - name: Start and enable redis service on RedHat
      service:
        name: redis
        state: started
        enabled: true

    - name: Set fact after installation
      set_fact:
        redis_installed: true
      when: ansible_facts.services["redis.service"] is defined
  when: (ansible_os_family | lower) == "redhat"

- name: Start and enable redis on Debian block
  block:
    - name: Start and enable redis-server service on Debian
      service:
        name: redis-server
        state: started
        enabled: true

    - name: Set fact after installation
      set_fact:
        redis_installed: true
      when: ansible_facts.services["redis-server.service"] is defined
  when: (ansible_os_family | lower) == "debian"
