---

- name: Fail when both cluster_enabled and sentinel_enabled true
  fail:
    msg: >
      Both cluster_enabled and sentinel_enabled flags can not be true. Set one of
      them or both as false.
  when:
    - sentinel_enabled | bool
    - cluster_enabled | bool

- name: Include install_main.yml file conditionally
  include_tasks: install_main.yml
  when: (install_redis | bool)

- name: Include uninstall_main.yml file conditionally
  include_tasks: uninstall_main.yml
  when: not (install_redis | bool)
