---

- name: Include install.yml file conditionally
  include_tasks: install.yml
  when: (redis_install | bool)

- name: Include uninstall.yml file conditionally
  include_tasks: uninstall.yml
  when: not (redis_install | bool)

...
