---

- name: Set required kernel parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
  ignore_errors: true
  loop: "{{ os_required_parameters }}"
