---

- name: Remove Redis
  block:
    - name: Ensure redis service is stopped and disabled
      service:
        name: redis
        state: stopped
        enabled: false

    - name: Ensure redis-sentinel service is stopped and disabled
      service:
        name: redis-sentinel
        state: stopped
        enabled: false
      when: sentinel_enabled | bool

    - name: Include version specific variables for CentOS/RHEL
      include_vars: "redhat_{{ ansible_distribution_major_version }}.yml"

    - name: Revoke firewalld permissions if firewalld is running
      firewalld:
        port: "{{ redis_port }}/tcp"
        permanent: true
        immediate: true
        state: disabled
      when: ansible_facts.services["firewalld.service"].state == "running"

    - name: Revoke firewalld permissions if firewalld is running when sentinel enabled
      firewalld:
        port: "{{ sentinel_port }}/tcp"
        permanent: true
        immediate: true
        state: disabled
      when:
        - sentinel_enabled | bool
        - ansible_facts.services["firewalld.service"].state == "running"

    - name: Revoke firewalld permissions if firewalld is running when cluster enabled
      firewalld:
        port: "{{ cluster_bus_port }}/tcp"
        permanent: true
        immediate: true
        state: disabled
      when:
        - cluster_enabled | bool
        - ansible_facts.services["firewalld.service"].state == "running"

    - name: Revoke redis port for SELinux
      seport:
        ports: "{{ redis_port }}"
        proto: tcp
        setype: redis_port_t
        state: absent
      when:
        - ansible_selinux is defined
        - ansible_selinux | bool

    - name: Remove transferred files and created directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ redis_dest_file }}"
        - "{{ sentinel_dest_file }}"
        - "{{ redis_log_file }}"
        - "{{ sentinel_log_file }}"
        - /etc/tuned/redis-server

    - name: Remove transferred files and created directories when sentinel enabled
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ sentinel_data_dir }}"
        - "{{ sentinel_log_file }}"

    - name: Remove redis package
      yum:
        name: redis
        state: absent

    - name: Ensure the redis user is removed
      user:
        name: redis
        state: absent
        remove: true

    - name: Ensure the redis group is removed
      group:
        name: redis
        state: absent

    - name: Ensure tuned is restarted
      systemd:
        name: tuned
        state: restarted
        daemon_reload: true

    - name: Set {{ os_tuned_default_profile }} as active tuned profile
      command: tuned-adm profile {{ os_tuned_default_profile }}

    - name: Disable swap block
      block:
        - name: Remove swap file entry in fstab
          mount:
            name: none
            src: "{{ os_swap_file_path }}"
            fstype: swap
            opts: sw
            state: absent

        - name: Disable swap
          command: swapoff -a
          tags: ['skip_ansible_lint']

        - name: Ensure swap file doesn't exist anymore
          file:
            path: "{{ os_swap_file_path }}"
            state: absent
      when: (os_disable_swap | bool) and ansible_swaptotal_mb != 0
  rescue:
    - name: Print error message and fail
      fail:
        msg: "Got an error inside block, try to rerun tasks with -v option"
  when: ansible_facts.services["redis.service"] is defined
