---

- name: start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - redis
    - redis-sentinel

#- name: start and enable disable-thp service
#  service:
#    name: disable-thp
#    state: started
#    enabled: true

...
