---

- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Install package
      pip:
        name: python3-apt
  roles:
    - role: bilalcaliskan.redis
      vars:
        os_enable_tuned: false
        os_disable_swap: false
