---

- name: Verify
  hosts: all
  become: true
  vars:
    data:
      - key: key1
        value: value1
      - key: key2
        value: value2
      - key: key3
        value: value3
  tasks:
    - name: Ensure redis and sentinel ports are reachable
      wait_for:
        host: localhost
        port: "{{ item }}"
        timeout: 3
      register: connectivity_result
      loop:
        - 6379
        - 16379

    - name: Ensure redis-py python package is installed
      pip:
        name: redis-py

    - name: Configure local redis to have 10000 max clients
      redis:
        command: config
        name: maxclients
        value: 10000

    - name: Set couple of keys
      command: "redis-cli {{ item.key }} {{ item.value }}"
      loop: "{{ data }}"
      when: connectivity_result is succeeded

    - name: Flush all the redis db
      redis:
        command: flush
        flush_mode: all

...
