---

- name: Verify
  hosts: all
  become: true
  vars:
    data:
      - key: key1
        value: value1
      - key: key2
        value: value2
      - key: key3
        value: value3
  tasks:
    - name: Ensure redis and sentinel ports are reachable
      wait_for:
        host: localhost
        port: "{{ item }}"
        timeout: 3
      register: connectivity_result
      loop:
        - 6379
        - 16379

    - name: Set couple of keys
      command: "redis-cli {{ item.key }} {{ item.value }}"
      loop: "{{ data }}"
      when: connectivity_result is succeeded
